---
- name: app-php docker install
  hosts: all
  vars_files:
    - vars/default.yml
  become: true
  vars:
    ansible_ssh_pipelining: true
  tasks:
    - name: Install packages pip
      ansible.builtin.apt:
        name:
          - python3-pip
        state: present
    - name: Install python and pip
      ansible.builtin.apt:
        name:
          - python3
          - python3-pip
          - python3-setuptools
        state: present
        update_cache: true
    - name: Install docker sdk
      pip:
        name: 
          - docker
          - requests
          - docker-compose
    - name: Start docker service
      service:
        name: docker
        state: started